# The top-level targets paths.
add:
  fulcio.crt.pem:
    sigstore:
      uri: https://fulcio.sigstage.dev
      usage: Fulcio
      status: Active
  fulcio_intermediate.crt.pem:
    sigstore:
      uri: https://fulcio.sigstage.dev
      usage: Fulcio
      status: Active
  ctfe.pub:
    sigstore:
      uri: https://ctfe.sigstage.dev/test
      usage: CTFE
      status: Active
  ctfe_2022.pub:
    sigstore:
      uri: https://ctfe.sigstage.dev/2022
      usage: CTFE
      status: Active
  ctfe_2022_2.pub:
    sigstore:
      uri: https://ctfe.sigstage.dev/2022-2
      usage: CTFE
      status: Active
  rekor.pub:
    sigstore:
      uri: https://rekor.sigstage.dev
      usage: Rekor
      status: Active
  trusted_root.json:
