name: TUF-on-CI publish

permissions: {}

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: false

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - id: build-and-upload-repository
        uses: theupdateframework/tuf-on-ci/actions/upload-repository@89d2dad3c8b626dde7a9e65b036ca35d11ab8b2a # v0.12.0
        with:
          gh_pages: true
          ref: ${{ inputs.ref }}
          metadata_path: './'

  deploy-to-pages:
    permissions:
      pages: write
      id-token: write # for authenticating to GH Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy TUF-on-CI repository to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

  test-deployed-pages:
    needs: deploy-to-pages
    permissions:
      issues: 'write' # for modifying Issues
      id-token: 'write' # for signing with the GitHub Actions workflow identity
    uses: ./.github/workflows/test.yml

  # disabled during migration
  # (when enabling remember to add to update-issue.needs)
  #deploy-to-gcs:
  #  needs: [test-deployed-pages]
  #  permissions:
  #    id-token: 'write' # for authenticating with OIDC
  #  uses: ./.github/workflows/deploy-to-gcs.yml

  #test-deployed-gcs:
  #  needs: [deploy-to-gcs]
  #  if: always() && !failure() && !cancelled()
  #  permissions:
  #    issues: 'write' # for modifying Issues
  #    id-token: 'write' # for signing with the GitHub Actions workflow identity
  #  uses: ./.github/workflows/test-gcs.yml

  update-issue:
    runs-on: ubuntu-latest
    needs: [build, deploy-to-pages, test-deployed-pages]
    if: always() && !cancelled()
    permissions:
      issues: 'write' # for modifying Issues
    steps:
      - name: Update the issue for the workflow
        uses: theupdateframework/tuf-on-ci/actions/update-issue@89d2dad3c8b626dde7a9e65b036ca35d11ab8b2a # v0.12.0
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
          success: ${{ !contains(needs.*.result, 'failure') }}
