name: root-signing GCS repository tests

on:
  workflow_call:
  workflow_dispatch:
  # disabled during migration
  #schedule:
  #  - cron: '17 4,10,16,22 * * *'

permissions: {}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set initial root for the smoke test
        run: cp metadata/root_history/5.root.json ./root.json

      - name: Smoke test Sigstore TUF repository with a TUF client
        uses: theupdateframework/tuf-on-ci/actions/test-repository@89d2dad3c8b626dde7a9e65b036ca35d11ab8b2a # v0.12.0
        with:
          metadata_url: https://tuf-repo-cdn.sigstore.dev/
          valid_days: 3
          offline_valid_days: 30

  custom-smoke-test:
    permissions:
      id-token: 'write' # For signing with the GitHub workflow identity
    uses: ./.github/workflows/custom-test.yml
    with:
      metadata_url: https://tuf-repo-cdn.sigstore.dev/

  update-issue:
    runs-on: ubuntu-latest
    needs: [smoke-test, custom-smoke-test]
    # During workflow_call, caller updates issue
    if: always() && !cancelled() && github.workflow == 'root-signing GCS repository tests'
    permissions:
      issues: 'write' # for modifying Issues
    steps:
      - name: Update the issue for the workflow
        uses: theupdateframework/tuf-on-ci/actions/update-issue@89d2dad3c8b626dde7a9e65b036ca35d11ab8b2a # v0.12.0
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
          success: ${{ !contains(needs.*.result, 'failure') }}
